name: Tests

on:
  push:
    branches: [ main, update-from-18.01 ]
  pull_request:
    branches: [ main, update-from-18.01 ]

jobs:
  test:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: List available simulators
      run: xcrun simctl list devices available
    - name: Check Xcode
      run: /usr/bin/xcodebuild -version
    - name: Run tests
      run: |
        xcodebuild test \
          -project CarsharingAfon.xcodeproj \
          -scheme CarsharingAfon \
          -destination 'platform=iOS Simulator,name=iPhone SE (3rd generation),OS=18.5' \
          -enableCodeCoverage YES 2>&1
          | tee xcodebuild.log
    - name: Upload logs if failed
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: xcodebuild-log
        path: xcodebuild.log
